[versions]
# Plugins
fabricLoom = "1.14-SNAPSHOT"
spotless = "8.1.0"

# Libraries
minecraft = "26.1-snapshot-1"
fabricLoader = "0.18.4"
fabricApi = "0.140.2+26.1"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }

[plugins]
fabricLoom = { id = "net.fabricmc.fabric-loom", version.ref = "fabricLoom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[bundles]
