[versions]
# Plugins
fabricLoom = "1.12-SNAPSHOT"
spotless = "8.1.0"

# Libraries
minecraft = "1.21.10"
fabricYarn = "1.21.10+build.3"
fabricLoader = "0.17.3"
fabricApi = "0.136.0+1.21.10"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabricYarn = { group = "net.fabricmc", name = "yarn", version.ref = "fabricYarn" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }

[plugins]
fabricLoom = { id = "fabric-loom", version.ref = "fabricLoom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[bundles]
